#!/bin/bash

set -eu
FULL_FILEPATH="$1"
PUBLIC_KEY_FILEPATH="$2"
KEYS_TO_ENCRYPT="$3"

echo "FULL_FILEPATH =  ${FULL_FILEPATH}"
echo "PUBLIC_KEY_FILEPATH = ${PUBLIC_KEY_FILEPATH}"
echo "KEYS_TO_ENCRYPT = ${KEYS_TO_ENCRYPT}"
echo "Hello World"