name: push-to-remote

on:
# Trigger workflow manually
 workflow_dispatch: 

jobs:

  sftp-compose-project-to-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: mp30028/sopsage/.github/actions/sftp-to-remote@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          local_filepath: ./compose-sops-and-age
          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}/sopsage/staging
          
  sftp-configs-to-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mp30028/sopsage/.github/actions/sftp-to-remote@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          local_filepath: ./_configs
          remote_filepath: ${{ vars.REMOTE_FILEPATH  }}/sopsage/staging
          
  merge-staging-to-operational-folders:
    runs-on: ubuntu-latest
    needs: 
    - sftp-compose-project-to-staging
    - sftp-configs-to-staging
    
    steps:
      - uses: actions/checkout@v3
      - uses: mp30028/sopsage/.github/actions/execute-remote-command@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_host: ${{ secrets.REMOTE_SERVER  }}
          remote_port: ${{ secrets.REMOTE_PORT  }}
          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
          remote_cmd: mkdir -p /installed-apps/sopsage/configs /installed-apps/sopsage/compose; cp -rfp ${{ vars.REMOTE_FILEPATH  }}/sopsage/staging/_configs/* ${{ vars.REMOTE_FILEPATH  }}/sopsage/configs;cp -rfp ${{ vars.REMOTE_FILEPATH  }}/sopsage/staging/compose-sops-and-age/* ${{ vars.REMOTE_FILEPATH  }}/sopsage/compose; rm -rf ${{ vars.REMOTE_FILEPATH  }}/sopsage/staging

#  generate-key-pair:
#
#    runs-on: ubuntu-latest
#    needs: [sftp-artifacts-to-remote]
#    steps:      
#      - uses: mp30028/sopsage-tmp/.github/actions/execute-remote-command@main
#        with:
#          remote_username: ${{ secrets.REMOTE_USERNAME  }}
#          remote_host: ${{ secrets.REMOTE_SERVER  }}
#          remote_port: ${{ secrets.REMOTE_PORT  }}
#          remote_ssh_key: ${{ secrets.REMOTE_SSH_KEY  }}
#          remote_cmd: ${{ vars.REMOTE_FILEPATH  }}/setup-sops-and-age/generate-key-pair.sh
